### ISSUE TITLE
推荐参考 杭电 培养指南

### ISSUE THREAD

**Issue by sanbuphy** [west2-online/fzu-run#2]
fzu 老学长一枚，强烈推荐 hdu

https://github.com/camera-2018/hdu-cs-wiki

https://wiki.xyxsw.site/

**Comment by ozline** [comment]
感谢推荐！这边我会做一个参考的

**Comment by sanbuphy** [comment]
> 感谢推荐！这边我会做一个参考的

祝顺利。
